### ISSUE TITLE
mdformat checks fail on github actions but not locally

### ISSUE THREAD

**Issue by MikhailZex** [hukkinj1/mdformat-gfm#6] opened 2021-03-31 18:53 UTC
- Github Actions [on this commit](https://github.com/spotDL/spotdlRedesign/runs/2239754784?check_suite_focus=true):
    ![image](https://user-images.githubusercontent.com/52100648/113195717-38b83e80-9280-11eb-8a45-a1d55adbf13c.png)

- Local run:
    ![image](https://user-images.githubusercontent.com/52100648/113195813-5a192a80-9280-11eb-9c7e-ddeb80f90161.png)

Any help appriciated.

**Comment by MikhailZex** [comment] 2021-03-31 19:02
Update: I uninstalled/reinstalled `mdformat-gfm` & `mdformat-toc`, the local run threw the same errors:
![image](https://user-images.githubusercontent.com/52100648/113196623-589c3200-9281-11eb-8ab9-5f6827fae4c9.png)

The thing is everything reinstalled is just old cached wheels, so I didn't really update anything. I'm not sure why `mdformat` glitched out on multiple runs just now.

**Comment by hukkinj1** [comment] 2021-03-31 19:04
I'm pretty sure this is due to a recent `mdformat-toc` release that removes needless angle brackets from toc link destinations. You might want to use a lockfile in CI if you want to be sure the installation is reproducible.

**Comment by hukkinj1** [comment] 2021-03-31 19:09
BTW, with the latest mdformat (0.6.3) you can run `mdformat --version` to print all installed plugins and their versions. Could be useful debugging.

**Comment by hukkinj1** [comment] 2021-03-31 19:30
I'll close this now, but please make another report /  issue if you think this is anything else but a version mismatch.

**Closed by hukkinj1** 2021-03-31 19:30 UTC

**Comment by MikhailZex** [comment] 2021-04-01 00:34
> Update: I uninstalled/reinstalled `mdformat-gfm` & `mdformat-toc`, the local run threw the same errors:
> ![image](https://user-images.githubusercontent.com/52100648/113196623-589c3200-9281-11eb-8ab9-5f6827fae4c9.png)
> 
> The thing is everything reinstalled is just old cached wheels, so I didn't really update anything. I'm not sure why `mdformat` glitched out on multiple runs just now.

As you can see in the screenshot nothing is updated, everything is merely ***reinstalled from cache***. As far as I understand that means that no package has been updated to a newer version.

I could definitely be wrong but I thought it was worth pointing out.

**Comment by MikhailZex** [comment] 2021-04-01 00:35
> BTW, with the latest mdformat (0.6.3) you can run `mdformat --version` to print all installed plugins and their versions. Could be useful debugging.

This should be super helpful. Thanks.

**Comment by hukkinj1** [comment] 2021-04-01 01:15
> As you can see in the screenshot nothing is updated, everything is merely reinstalled from cache. As far as I understand that means that no package has been updated to a newer version

Ah but that screenshot shows though that the cached `mdformat-toc` version is 0.2.2 which is the first version to remove the redundant angle brackets. Since the brackets were still in place in that commit, it makes sense for the check to fail.

Like said, the way to avoid this in the future is either to pin versions in CI, or alternatively whenever this occurs, install updated versions from pip, format locally, and make another commit.

> This should be super helpful. Thanks.

Glad to be helpful :smile_cat:
